### ISSUE TITLE
Hello there

### ISSUE THREAD

**Issue by nemchik** [imagegenius/.github#1]
I'm interested in what you've got going on here. I'd love to have a chat. Are you on Discord, or another chat platform where we could connect?

**Comment by hydazz** [comment]
you can add me on discord: `aHlkYXojMjQzMQoKKEhvcGUgSSdtIG5vdCBpbiB0cm91YmxlIDooKQ==`

**Comment by nemchik** [comment]
Thank you for replying. I've sent a request to message you.
