### ISSUE TITLE
[Request] All-in-one Paperless-ngx

### ISSUE THREAD

**Issue by rursache** [imagegenius/.github#2]
Hi,

I love your work with the Immich AIO image. Any chance you'll take the same approach for Paperless-ngx?

Thanks

**Comment by hydazz** [comment]
Do you know what happened to https://github.com/linuxserver/docker-paperless-ngx?

**Comment by rursache** [comment]
> do you know why it was deprecated?

AFAIK they said on discord that the member using and maintaining it stopped using paperless ngx and no one offered to maintain it

**Comment by rursache** [comment]
@hydazz seems like I was wrong
https://info.linuxserver.io/issues/2022-09-05-paperless-ngx/

**Comment by hydazz** [comment]
Ill give it a shot
https://github.com/imagegenius/docker-paperless-ngx

**Comment by rursache** [comment]
> Ill give it a shot https://github.com/imagegenius/docker-paperless-ngx

thanks for your work and effort!
